# Generated by Django 2.2.7 on 2023-02-02 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_auto_20230202_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyCode', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('clinicalTrials', models.CharField(blank=True, max_length=40)),
                ('eudraCT', models.CharField(blank=True, max_length=40)),
                ('disease', models.CharField(blank=True, max_length=100)),
                ('hopt_studyid', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='TrialPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(choices=[(0, 'view'), (1, 'change (and view)'), (2, 'delete, (and view + change'), (3, 'admin, (and view + change + delete)')], default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trial_createdBy', to=settings.AUTH_USER_MODEL)),
                ('trial', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trials.Trial')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/trials/%Y/%m/%d')),
                ('description', models.TextField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trial', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trials.Trial')),
                ('uploaded_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
