# Generated by Django 2.2.1 on 2019-07-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0004_auto_20190706_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='clinicalTrials',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='trial',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='eudraCT',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
