# Generated by Django 2.2.1 on 2019-08-14 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0006_document_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='trial',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='trials.Trial'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
