# Generated by Django 2.2.1 on 2019-08-14 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0007_auto_20190814_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='trial',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trials.Trial'),
        ),
    ]
