# Generated by Django 2.2.1 on 2019-09-11 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trials', '0008_auto_20190814_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents'),
        ),
        migrations.CreateModel(
            name='TrialPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(choices=[(0, 'access'), (1, 'edit'), (2, ' delete'), (3, 'admin')], default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trial_createdBy', to=settings.AUTH_USER_MODEL)),
                ('trial', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trials.Trial')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
