# Generated by Django 2.2.1 on 2019-09-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0009_auto_20190911_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/trials/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='trialpermission',
            name='permission',
            field=models.IntegerField(choices=[(0, 'view'), (1, 'change (and view)'), (2, 'delete, (and view + change'), (3, 'admin, (and view + change + delete)')], default=0),
        ),
    ]
