# Generated by Django 2.2.7 on 2019-11-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0010_auto_20190911_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='hopt_studyid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
