# Generated by Django 2.2.7 on 2019-11-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0011_trial_hopt_studyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='disease',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
