# Generated by Django 2.2.7 on 2021-04-11 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_auto_20210326_0951'),
        ('trials', '0012_trial_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
