# Generated by Django 2.2.1 on 2019-05-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashsimplemodel',
            name='x',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dashsimplemodel',
            name='y',
            field=models.IntegerField(default=1),
        ),
    ]
