# Generated by Django 2.2.7 on 2023-02-02 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trials', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameterName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiagType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagTypeName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TreatMedication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetId', models.CharField(max_length=40)),
                ('dateBegin', models.DateField()),
                ('dateEnd', models.DateField(blank=True, null=True)),
                ('interval', models.IntegerField(blank=True, null=True)),
                ('intervalUnit', models.CharField(blank=True, max_length=20, null=True)),
                ('drugName', models.CharField(blank=True, max_length=40, null=True)),
                ('dosage', models.IntegerField(blank=True, null=True)),
                ('dosageUnit', models.CharField(blank=True, max_length=20, null=True)),
                ('medScheme', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trials.Trial')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetId', models.CharField(max_length=40)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True)),
                ('trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trials.Trial')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetId', models.CharField(max_length=40)),
                ('sampleId', models.CharField(max_length=40)),
                ('sampleDate', models.DateField()),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('diagType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbviews.DiagType')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbviews.DiagParameter')),
                ('trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trials.Trial')),
            ],
        ),
    ]
