# Generated by Django 2.2.7 on 2020-04-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmedication',
            name='intervalUnit',
            field=models.CharField(max_length=20),
        ),
    ]
