# Generated by Django 2.2.7 on 2020-04-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbviews', '0003_auto_20200428_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmedication',
            name='dateEnd',
            field=models.DateField(blank=True, null=True),
        ),
    ]
