# Generated by Django 2.2.7 on 2020-04-28 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbviews', '0004_auto_20200428_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameterName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiagType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagTypeName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetId', models.CharField(max_length=40)),
                ('sampleId', models.CharField(max_length=40)),
                ('sampleDate', models.DateField()),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('diagType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbviews.DiagType')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbviews.DiagParameter')),
            ],
        ),
    ]
