# Generated by Django 2.2.7 on 2021-04-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbviews', '0005_diagnostic_diagparameter_diagtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmedication',
            name='dosage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatmedication',
            name='dosageUnit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='treatmedication',
            name='drugName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='treatmedication',
            name='interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatmedication',
            name='intervalUnit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='treatmedication',
            name='medScheme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
