# Generated by Django 2.2.7 on 2021-05-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbviews', '0006_auto_20210423_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
