# Generated by Django 2.2.7 on 2021-06-07 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0014_auto_20210411_2034'),
        ('dbviews', '0007_auto_20210503_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='trialId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trials.Trial'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='diagType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbviews.DiagType'),
        ),
    ]
