# Generated by Django 2.2.7 on 2021-06-07 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0014_auto_20210411_2034'),
        ('dbviews', '0008_auto_20210607_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmedication',
            name='trialId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trials.Trial'),
        ),
    ]
