# Generated by Django 2.2.7 on 2021-06-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbviews', '0009_treatmedication_trialid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostic',
            old_name='trialId',
            new_name='trial',
        ),
        migrations.RenameField(
            model_name='treatmedication',
            old_name='trialId',
            new_name='trial',
        ),
    ]
