# Generated by Django 2.2.7 on 2021-06-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbviews', '0010_auto_20210607_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTrials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetId', models.CharField(max_length=40)),
            ],
        ),
    ]
