# Generated by Django 2.2.7 on 2021-06-08 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0014_auto_20210411_2034'),
        ('dbviews', '0011_patienttrials'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttrials',
            name='trial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trials.Trial'),
        ),
    ]
