# Generated by Django 2.2.7 on 2021-06-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0014_auto_20210411_2034'),
        ('dbviews', '0012_patienttrials_trial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientTrials',
            new_name='PatientTrial',
        ),
    ]
