# Generated by Django 2.2.7 on 2021-06-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbviews', '0013_auto_20210608_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttrial',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True),
        ),
    ]
